name: Prettier formatter

on:
  pull_request:
    branches:
      - main
    permissions:
      contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          ref: ${{ github.head_ref }}

      - name: Prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,jsx,ts,tsx,css,scss,md,json,yml,yaml}